server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7900/eureka/
    registry-fetch-interval-seconds: 30
    enabled: false
      #,http://localhost:7901/eureka/,http://localhost:7902/eureka/
  instance:
    lease-renewal-interval-in-seconds: 30

spring:
  application:
    name: api-passenger
logging:
  level:
    org.springframework: debug

